import fs from 'fs/promises';
import path from 'path';
import type { RankedApplication } from '../types.js';
import { logger } from '../observability/logger.js';

/**
 * Export pipelines for generating reports and artifacts
 */

const PRIVACY_DISCLAIMER = `---
**Privacy Notice:** This document contains confidential information. Do not share publicly.
---

`;

/**
 * Get emoji badge for rank
 */
function getRankBadge(rank: number): string {
  if (rank === 1) return '🥇';
  if (rank === 2) return '🥈';
  if (rank === 3) return '🥉';
  return `${rank}.`;
}

/**
 * Export leaderboard.md
 */
export async function exportLeaderboard(
  ranked: RankedApplication[],
  outputDir: string
): Promise<void> {
  logger.info('Exporting leaderboard');

  let content = `# Application Leaderboard\n\n`;
  content += PRIVACY_DISCLAIMER;
  content += `Generated: ${new Date().toISOString()}\n\n`;
  content += `Total applications: ${ranked.length}\n\n`;

  content += `## Rankings\n\n`;

  for (const app of ranked) {
    const badge = getRankBadge(app.rank);
    const bandEmoji = app.band === 'GO' ? '✅' : app.band === 'WAITLIST' ? '⏸️' : '❌';
    
    content += `### ${badge} ${app.app.company} - ${app.score.weighted_total_0to100}/100 ${bandEmoji}\n\n`;
    content += `- **Founder:** ${app.app.founderName}\n`;
    content += `- **Region:** ${app.app.region}\n`;
    content += `- **Stage:** ${app.app.stage}\n`;
    content += `- **Decision:** ${app.band}\n`;
    content += `- **Summary:** ${app.score.summary}\n\n`;
    
    if (app.score.red_flags && app.score.red_flags.length > 0) {
      content += `**🚩 Red Flags:**\n`;
      for (const flag of app.score.red_flags) {
        content += `- ${flag}\n`;
      }
      content += `\n`;
    }
  }

  content += `\n---\n*Generated by Gloven CLI*\n`;

  const filePath = path.join(outputDir, 'leaderboard.md');
  await fs.writeFile(filePath, content, 'utf-8');
  logger.info(`Leaderboard exported to ${filePath}`);
}

/**
 * Export shortlist.csv (GO decisions only)
 */
export async function exportShortlist(
  ranked: RankedApplication[],
  outputDir: string
): Promise<void> {
  logger.info('Exporting shortlist');

  const goApps = ranked.filter(app => app.band === 'GO');
  
  let csv = 'rank,company,founder,email,region,stage,score,team_score,problem_score,traction_score\n';
  
  for (const app of goApps) {
    const row = [
      app.rank,
      `"${app.app.company}"`,
      `"${app.app.founderName}"`,
      app.app.email,
      app.app.region,
      app.app.stage,
      app.score.weighted_total_0to100,
      app.score.team.score,
      app.score.problem_size.score,
      app.score.traction.score,
    ].join(',');
    
    csv += row + '\n';
  }

  const filePath = path.join(outputDir, 'shortlist.csv');
  await fs.writeFile(filePath, csv, 'utf-8');
  logger.info(`Shortlist exported to ${filePath} (${goApps.length} applications)`);
}

/**
 * Export triage.md (WAITLIST with follow-up questions)
 */
export async function exportTriage(
  ranked: RankedApplication[],
  outputDir: string
): Promise<void> {
  logger.info('Exporting triage list');

  const waitlistApps = ranked.filter(app => app.band === 'WAITLIST');
  
  let content = `# Triage List - WAITLIST Applications\n\n`;
  content += PRIVACY_DISCLAIMER;
  content += `Generated: ${new Date().toISOString()}\n\n`;
  content += `Applications requiring follow-up: ${waitlistApps.length}\n\n`;

  for (const app of waitlistApps) {
    content += `## ${app.app.company} (Rank #${app.rank})\n\n`;
    content += `- **Founder:** ${app.app.founderName}\n`;
    content += `- **Email:** ${app.app.email}\n`;
    content += `- **Score:** ${app.score.weighted_total_0to100}/100\n`;
    content += `- **Region:** ${app.app.region} | **Stage:** ${app.app.stage}\n\n`;
    
    content += `**Assessment:**\n${app.score.summary}\n\n`;
    
    if (app.score.followup_questions && app.score.followup_questions.length > 0) {
      content += `**Follow-up Questions:**\n`;
      for (const question of app.score.followup_questions) {
        content += `- [ ] ${question}\n`;
      }
      content += `\n`;
    }
    
    content += `---\n\n`;
  }

  content += `\n*Generated by Gloven CLI*\n`;

  const filePath = path.join(outputDir, 'triage.md');
  await fs.writeFile(filePath, content, 'utf-8');
  logger.info(`Triage list exported to ${filePath} (${waitlistApps.length} applications)`);
}

/**
 * Export flags.md (Apps with red flags)
 */
export async function exportFlags(
  ranked: RankedApplication[],
  outputDir: string
): Promise<void> {
  logger.info('Exporting red flags report');

  const flaggedApps = ranked.filter(
    app => app.score.red_flags && app.score.red_flags.length > 0
  );
  
  let content = `# Red Flags Report\n\n`;
  content += PRIVACY_DISCLAIMER;
  content += `Generated: ${new Date().toISOString()}\n\n`;
  content += `Applications with red flags: ${flaggedApps.length}\n\n`;

  if (flaggedApps.length === 0) {
    content += `✅ No red flags identified in current batch.\n`;
  } else {
    for (const app of flaggedApps) {
      content += `## ${app.app.company} (Rank #${app.rank})\n\n`;
      content += `- **Founder:** ${app.app.founderName}\n`;
      content += `- **Email:** ${app.app.email}\n`;
      content += `- **Decision:** ${app.band}\n`;
      content += `- **Score:** ${app.score.weighted_total_0to100}/100\n\n`;
      
      content += `**🚩 Red Flags:**\n`;
      for (const flag of app.score.red_flags!) {
        content += `- ${flag}\n`;
      }
      content += `\n`;
      
      content += `**Summary:** ${app.score.summary}\n\n`;
      content += `---\n\n`;
    }
  }

  content += `\n*Generated by Gloven CLI*\n`;

  const filePath = path.join(outputDir, 'flags.md');
  await fs.writeFile(filePath, content, 'utf-8');
  logger.info(`Red flags report exported to ${filePath} (${flaggedApps.length} flagged)`);
}

/**
 * Export all reports
 */
export async function exportAll(
  ranked: RankedApplication[],
  outputDir: string
): Promise<void> {
  // Ensure output directory exists
  await fs.mkdir(outputDir, { recursive: true });

  await Promise.all([
    exportLeaderboard(ranked, outputDir),
    exportShortlist(ranked, outputDir),
    exportTriage(ranked, outputDir),
    exportFlags(ranked, outputDir),
  ]);

  logger.info('All exports complete');
}